repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.58.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: checkov
    - id: terraform_tflint
    - id: terraform_tfsec
